links:
  - from: ~/dotfiles/config/ideavimrc
    to: ~/.ideavimrc
  - from: ~/dotfiles/config/git/gitignore_global
    to: ~/.gitignore
  - from: ~/dotfiles/config/teleport.yaml
    to: ~/.teleport.yaml
  - from: ~/dotfiles/config/zsh/zshrc
    to: ~/.zshrc
  - from: ~/dotfiles/config/tmux/tmux.conf
    to: ~/.tmux.conf
  - from: ~/dotfiles/config/zellij/config.kdl
    to: ~/.config/zellij/config.kdl
